copy intern\ghost\intern\GHOST_EventDragnDrop.h J:\Blender---Layer\intern\ghost\intern /Y
copy release\scripts\startup\bl_ui\space_image.py J:\Blender---Layer\release\scripts\startup\bl_ui /Y
copy release\scripts\startup\bl_ui\space_userpref.py J:\Blender---Layer\release\scripts\startup\bl_ui /Y
copy release\scripts\startup\bl_ui\space_view3d_toolbar.py J:\Blender---Layer\release\scripts\startup\bl_ui /Y
copy source\blender\blenkernel\BKE_bmfont_types.h J:\Blender---Layer\source\blender\blenkernel /Y
copy source\blender\blenkernel\BKE_image.h J:\Blender---Layer\source\blender\blenkernel /Y
copy source\blender\blenkernel\BKE_layer.h J:\Blender---Layer\source\blender\blenkernel /Y
copy source\blender\blenkernel\CMakeLists.txt J:\Blender---Layer\source\blender\blenkernel /Y
copy source\blender\blenkernel\intern\bmfont.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\brush.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\colortools.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\dynamicpaint.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\icons.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\image.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\layer.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\library.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\movieclip.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\ocean.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\seqcache.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\seqeffects.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\seqmodifier.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\sequencer.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\tracking.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\writeffmpeg.c J:\Blender---Layer\source\blender\blenkernel\intern /Y
copy source\blender\blenlib\BLI_math_color.h J:\Blender---Layer\source\blender\blenlib /Y
copy source\blender\blenlib\intern\math_color.c J:\Blender---Layer\source\blender\blenlib\intern /Y
copy source\blender\blenlib\intern\math_color_inline.c J:\Blender---Layer\source\blender\blenlib\intern /Y
copy source\blender\blenloader\intern\readfile.c J:\Blender---Layer\source\blender\blenloader\intern /Y
copy source\blender\blenloader\intern\writefile.c J:\Blender---Layer\source\blender\blenloader\intern /Y
copy source\blender\collada\ImageExporter.cpp J:\Blender---Layer\source\blender\collada /Y
copy source\blender\compositor\nodes\COM_ImageNode.cpp J:\Blender---Layer\source\blender\compositor\nodes /Y
copy source\blender\compositor\operations\COM_ImageOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_KeyingScreenOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_MaskOperation.h J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_MovieClipOperation.h J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_MultilayerImageOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_OutputFileOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_PreviewOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_SplitOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\compositor\operations\COM_ViewerOperation.cpp J:\Blender---Layer\source\blender\compositor\operations /Y
copy source\blender\editors\include\BIF_glutil.h J:\Blender---Layer\source\blender\editors\include /Y
copy source\blender\editors\include\ED_image.h J:\Blender---Layer\source\blender\editors\include /Y
copy source\blender\editors\include\UI_resources.h J:\Blender---Layer\source\blender\editors\include /Y
copy source\blender\editors\interface\interface_draw.c J:\Blender---Layer\source\blender\editors\interface /Y
copy source\blender\editors\interface\interface_icons.c J:\Blender---Layer\source\blender\editors\interface /Y
copy source\blender\editors\interface\resources.c J:\Blender---Layer\source\blender\editors\interface /Y
copy source\blender\editors\mesh\editface.c J:\Blender---Layer\source\blender\editors\mesh /Y
copy source\blender\editors\mesh\editmesh_loopcut.c J:\Blender---Layer\source\blender\editors\mesh /Y
copy source\blender\editors\mesh\editmesh_select.c J:\Blender---Layer\source\blender\editors\mesh /Y
copy source\blender\editors\object\object_bake.c J:\Blender---Layer\source\blender\editors\object /Y
copy source\blender\editors\object\object_edit.c J:\Blender---Layer\source\blender\editors\object /Y
copy source\blender\editors\render\render_internal.c J:\Blender---Layer\source\blender\editors\render /Y
copy source\blender\editors\render\render_opengl.c J:\Blender---Layer\source\blender\editors\render /Y
copy source\blender\editors\render\render_preview.c J:\Blender---Layer\source\blender\editors\render /Y
copy source\blender\editors\render\render_shading.c J:\Blender---Layer\source\blender\editors\render /Y
copy source\blender\editors\screen\glutil.c J:\Blender---Layer\source\blender\editors\screen /Y
copy source\blender\editors\screen\screendump.c J:\Blender---Layer\source\blender\editors\screen /Y
copy source\blender\editors\sculpt_paint\paint_image.c J:\Blender---Layer\source\blender\editors\sculpt_paint /Y
copy source\blender\editors\sculpt_paint\paint_image_2d.c J:\Blender---Layer\source\blender\editors\sculpt_paint /Y
copy source\blender\editors\sculpt_paint\paint_image_proj.c J:\Blender---Layer\source\blender\editors\sculpt_paint /Y
copy source\blender\editors\sculpt_paint\paint_undo.c J:\Blender---Layer\source\blender\editors\sculpt_paint /Y
copy source\blender\editors\sculpt_paint\paint_vertex.c J:\Blender---Layer\source\blender\editors\sculpt_paint /Y
copy source\blender\editors\space_clip\clip_buttons.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\clip_draw.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\clip_editor.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\clip_ops.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\space_clip.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\tracking_ops.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_clip\tracking_select.c J:\Blender---Layer\source\blender\editors\space_clip /Y
copy source\blender\editors\space_file\file_draw.c J:\Blender---Layer\source\blender\editors\space_file /Y
copy source\blender\editors\space_file\filelist.c J:\Blender---Layer\source\blender\editors\space_file /Y
copy source\blender\editors\space_file\space_file.c J:\Blender---Layer\source\blender\editors\space_file /Y
copy source\blender\editors\space_image\image_buttons.c J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_image\image_draw.c J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_image\image_edit.c J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_image\image_intern.h J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_image\image_ops.c J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_image\space_image.c J:\Blender---Layer\source\blender\editors\space_image /Y
copy source\blender\editors\space_info\info_ops.c J:\Blender---Layer\source\blender\editors\space_info /Y
copy source\blender\editors\space_node\drawnode.c J:\Blender---Layer\source\blender\editors\space_node /Y
copy source\blender\editors\space_node\node_edit.c J:\Blender---Layer\source\blender\editors\space_node /Y
copy source\blender\editors\space_node\node_view.c J:\Blender---Layer\source\blender\editors\space_node /Y
copy source\blender\editors\space_sequencer\sequencer_draw.c J:\Blender---Layer\source\blender\editors\space_sequencer /Y
copy source\blender\editors\space_sequencer\sequencer_scopes.c J:\Blender---Layer\source\blender\editors\space_sequencer /Y
copy source\blender\editors\space_sequencer\sequencer_view.c J:\Blender---Layer\source\blender\editors\space_sequencer /Y
copy source\blender\editors\space_view3d\drawmesh.c J:\Blender---Layer\source\blender\editors\space_view3d /Y
copy source\blender\editors\space_view3d\drawobject.c J:\Blender---Layer\source\blender\editors\space_view3d /Y
copy source\blender\editors\space_view3d\view3d_draw.c J:\Blender---Layer\source\blender\editors\space_view3d /Y
copy source\blender\editors\space_view3d\view3d_select.c J:\Blender---Layer\source\blender\editors\space_view3d /Y
copy source\blender\editors\util\undo.c J:\Blender---Layer\source\blender\editors\util /Y
copy source\blender\freestyle\intern\application\AppView.cpp J:\Blender---Layer\source\blender\freestyle\intern\application /Y
copy source\blender\freestyle\intern\stroke\BasicStrokeShaders.cpp J:\Blender---Layer\source\blender\freestyle\intern\stroke /Y
copy source\blender\freestyle\intern\stroke\Canvas.cpp J:\Blender---Layer\source\blender\freestyle\intern\stroke /Y
copy source\blender\freestyle\intern\view_map\SteerableViewMap.cpp J:\Blender---Layer\source\blender\freestyle\intern\view_map /Y
copy source\blender\gpu\intern\gpu_draw.c J:\Blender---Layer\source\blender\gpu\intern /Y
copy source\blender\gpu\intern\gpu_material.c J:\Blender---Layer\source\blender\gpu\intern /Y
copy source\blender\imbuf\CMakeLists.txt J:\Blender---Layer\source\blender\imbuf /Y
copy source\blender\imbuf\IMB_imbuf.h J:\Blender---Layer\source\blender\imbuf /Y
copy source\blender\imbuf\intern\allocimbuf.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\anim_movie.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\bmp.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\cache.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\cineon\cineon_dpx.c J:\Blender---Layer\source\blender\imbuf\intern\cineon /Y
copy source\blender\imbuf\intern\colormanagement.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\dds\dds_api.cpp J:\Blender---Layer\source\blender\imbuf\intern\dds /Y
copy source\blender\imbuf\intern\dds\FlipDXT.cpp J:\Blender---Layer\source\blender\imbuf\intern\dds /Y
copy source\blender\imbuf\intern\divers.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\filetype.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\filter.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\imageprocess.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\IMB_anim.h J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\iris.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\jp2.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\jpeg.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\metadata.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\moviecache.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\offset.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\openexr\openexr_api.cpp J:\Blender---Layer\source\blender\imbuf\intern\openexr /Y
copy source\blender\imbuf\intern\png.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\radiance_hdr.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\readimage.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\rectop.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\rotate.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\scaling.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\targa.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\thumbs.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\thumbs_blend.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\tiff.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\util.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\imbuf\intern\writeimage.c J:\Blender---Layer\source\blender\imbuf\intern /Y
copy source\blender\makesdna\DNA_ID.h J:\Blender---Layer\source\blender\makesdna /Y
copy source\blender\makesdna\DNA_image_types.h J:\Blender---Layer\source\blender\makesdna /Y
copy source\blender\makesdna\DNA_imbuf_types.h J:\Blender---Layer\source\blender\makesdna /Y
copy source\blender\makesdna\DNA_userdef_types.h J:\Blender---Layer\source\blender\makesdna /Y
copy source\blender\makesdna\intern\makesdna.c J:\Blender---Layer\source\blender\makesdna\intern /Y
copy source\blender\makesrna\intern\rna_image.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_image_api.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_mask.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_movieclip.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_nodetree.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_sequencer_api.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_space.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_texture_api.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\intern\rna_userdef.c J:\Blender---Layer\source\blender\makesrna\intern /Y
copy source\blender\makesrna\RNA_access.h J:\Blender---Layer\source\blender\makesrna /Y
copy source\blender\nodes\composite\node_composite_util.h J:\Blender---Layer\source\blender\nodes\composite /Y
copy source\blender\nodes\composite\nodes\node_composite_image.c J:\Blender---Layer\source\blender\nodes\composite\nodes /Y
copy source\blender\nodes\composite\nodes\node_composite_outputFile.c J:\Blender---Layer\source\blender\nodes\composite\nodes /Y
copy source\blender\nodes\shader\node_shader_util.h J:\Blender---Layer\source\blender\nodes\shader /Y
copy source\blender\nodes\shader\nodes\node_shader_tex_environment.c J:\Blender---Layer\source\blender\nodes\shader\nodes /Y
copy source\blender\nodes\shader\nodes\node_shader_tex_image.c J:\Blender---Layer\source\blender\nodes\shader\nodes /Y
copy source\blender\nodes\shader\nodes\node_shader_texture.c J:\Blender---Layer\source\blender\nodes\shader\nodes /Y
copy source\blender\nodes\texture\node_texture_util.h J:\Blender---Layer\source\blender\nodes\texture /Y
copy source\blender\nodes\texture\nodes\node_texture_image.c J:\Blender---Layer\source\blender\nodes\texture\nodes /Y
copy source\blender\quicktime\apple\quicktime_export.c J:\Blender---Layer\source\blender\quicktime\apple /Y
copy source\blender\quicktime\quicktime_import.h J:\Blender---Layer\source\blender\quicktime /Y
copy source\blender\render\intern\source\bake.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\convertblender.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\envmap.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\external_engine.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\imagetexture.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\initrender.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\multires_bake.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\pipeline.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\pixelshading.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\render_result.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\render_texture.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\rendercore.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\render\intern\source\voxeldata.c J:\Blender---Layer\source\blender\render\intern\source /Y
copy source\blender\windowmanager\intern\wm_dragdrop.c J:\Blender---Layer\source\blender\windowmanager\intern /Y
copy source\blender\windowmanager\intern\wm_files.c J:\Blender---Layer\source\blender\windowmanager\intern /Y
copy source\blender\windowmanager\intern\wm_init_exit.c J:\Blender---Layer\source\blender\windowmanager\intern /Y
copy source\blender\windowmanager\intern\wm_operators.c J:\Blender---Layer\source\blender\windowmanager\intern /Y
copy source\blender\windowmanager\intern\wm_playanim.c J:\Blender---Layer\source\blender\windowmanager\intern /Y
copy source\gameengine\BlenderRoutines\KX_BlenderGL.cpp J:\Blender---Layer\source\gameengine\BlenderRoutines /Y
copy source\gameengine\Converter\BL_BlenderDataConversion.cpp J:\Blender---Layer\source\gameengine\Converter /Y
copy source\gameengine\GamePlayer\common\GPC_Canvas.cpp J:\Blender---Layer\source\gameengine\GamePlayer\common /Y
copy source\gameengine\Ketsji\BL_Material.cpp J:\Blender---Layer\source\gameengine\Ketsji /Y
copy source\gameengine\Ketsji\BL_Texture.cpp J:\Blender---Layer\source\gameengine\Ketsji /Y
copy source\gameengine\Ketsji\KX_PolygonMaterial.cpp J:\Blender---Layer\source\gameengine\Ketsji /Y
copy source\gameengine\VideoTexture\ImageBuff.cpp J:\Blender---Layer\source\gameengine\VideoTexture /Y
copy source\gameengine\VideoTexture\Texture.cpp J:\Blender---Layer\source\gameengine\VideoTexture /Y
del J:\Blender---Layer\source\blender\imbuf\IMB_imbuf_types.h
